name: ci

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Build
        run: |
          go build -trimpath main.go
          GOOS=windows GOARCH=amd64 go build -trimpath main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -o main-linux main.go
      - name: Upload Mac
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: main
      - name: Upload Win
        uses: actions/upload-artifact@v4
        with:
          name: win
          path: main.exe
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: main-linux
      