name: ci

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.github/**'
      - 'dev.md'
      - 'README.md'

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - name: Build
        run: sh build.sh
      - name: Upload Mac-go
        uses: actions/upload-artifact@v4
        with:
          name: mac-go
          path: main
      - name: Upload Win-go
        uses: actions/upload-artifact@v4
        with:
          name: win-go
          path: main.exe
      - name: Upload Linux-go
        uses: actions/upload-artifact@v4
        with:
          name: linux-go
          path: main-linux

  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm install && npm i pkg -g && npm dedupe && npm prune
      - name: build
        run: npm run pkg
      - name: Upload Mac-node
        uses: actions/upload-artifact@v4
        with:
          name: mac-node
          path: ./dist/typora-plugin-bilibili-macos
      - name: Upload Win-node
        uses: actions/upload-artifact@v4
        with:
          name: win-node
          path: ./dist/typora-plugin-bilibili-win.exe
      - name: Upload Linux-node
        uses: actions/upload-artifact@v4
        with:
          name: linux-node
          path: ./dist/typora-plugin-bilibili-linux
