name: release

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    tags:
      - "*"   #监听push tag的时候执行构建

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm install && npm i pkg -g
          npm run pkg
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/typora-plugin-bilibili-macos
            dist/typora-plugin-bilibili-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
